# Generated by Django 4.1.7 on 2023-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_comment_comment_rate_alter_post_content_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(
                choices=[("NW", "Новость"), ("AC", "Статья")], max_length=2
            ),
        ),
    ]
